version: "3.7"

services:
  sso:
    image: quay.io/keycloak/keycloak:22.0.0
    container_name: "keycloak"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
    command:
      - start-dev
    secrets:
      - keycloak_secrets
    environment:
      - KEYCLOAK_ADMIN=/run/secrets/KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD=run/secrets/KEYCLOAK_ADMIN_PASSWORD
      - PROXY_ADDRESS_FORWARDING=true
      # - VIRTUAL_HOST=run/secrets/HOST
      - VIRTUAL_PORT=run/secrets/PORT
    networks:
      - internal

  database:
    image: postgres:15
    container_name: "postgres"
    secrets:
      - db_secrets
    environment:
      - POSTGRES_USER=run/secrets/POSTGRES_USER
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_PASSWORD=run/secrets/POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
  # proxy:
  #   image: nginxproxy/nginx-proxy
  #   container_name: "nginx"
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   volumes:
  #     - conf:/etc/nginx/conf.d
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #     - certs:/etc/nginx/certs
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   networks:
  #     - internal

  # acme-companion:
  #   image: nginxproxy/acme-companion
  #   container_name: "acme-proxy"
  #   environment:
  #     - DEFAULT_EMAIL=amit@datenium.com
  #   volumes_from:
  #     - proxy
  #   volumes:
  #     - certs:/etc/nginx/certs
  #     - acme:/etc/acme.sh
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - internal

networks:
  internal:
    driver: bridge
    driver_opts:
      # Openstack spezifisch, kann auf 1500 gelassen werden wenn ihr auf
      # Bare Metal lauft. 
      com.docker.network.driver.mtu: 1450

secrets:
  keycloak_secrets:
    file: keycloak_secrets.txt
  db_secrets:
    file: db_secrets.txt

volumes:
  postgres_data:
  conf: # vhost:

  html:
    # certs:
    # acme:
