volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:15-alpine3.21
    restart: always
    container_name: postgres
    volumes:
      - ./.docker/postgres/db-data/:/var/lib/postgresql/data/:rw
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - 5434:5432

  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:latest
    restart: always
    container_name: keycloak
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${POSTGRESQL_DB}
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      KC_HOSTNAME: 'https://auth.nepdom.com/'
      KC_HOSTNAME_STRICT: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_LOG_LEVEL: INFO
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start", "--spi-email-template-provider=freemarker-plus-mustache", "--spi-email-template-freemarker-plus-mustache-enabled=true", "--spi-theme-cache-themes=false"]
    ports:
      - ${KEYCLOAK_PORT}:8080
      - ${KEYCLOAK_PORT_SSL}:8843
    depends_on:
      - postgres